import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import api from '../../api/client.js'
import FacilityChecklist from '../../components/FacilityChecklist.jsx'
import MultiImageUpload from '../../components/MultiImageUpload.jsx'
import Loader from '../../components/Loader.jsx'
import ConfirmDialog from '../../components/ConfirmDialog.jsx'

const emptyForm = { roomType:'', description:'', pricePerNight:'', maxOccupancy:2, totalUnits:1, facilities:[], images:[], breakfastIncluded:false, freeCancellation:true }
export default function OwnerHotelRooms() {
  const { id } = useParams(); const [hotel,setHotel]=useState(null); const [rooms,setRooms]=useState([]); const [loading,setLoading]=useState(true); const [master,setMaster]=useState([]); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState(null); const [form,setForm]=useState(emptyForm); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [deleteTarget,setDeleteTarget]=useState(null); const [preview,setPreview]=useState(null)
  function load(){setLoading(true);Promise.all([api.get(`/hotels/${id}`),api.get(`/hotels/${id}/rooms`)]).then(([h,r])=>{setHotel(h.data);setRooms(r.data)}).finally(()=>setLoading(false))}
  useEffect(()=>{load()},[id]); useEffect(()=>{api.get('/meta/room-facilities').then(r=>setMaster(r.data)).catch(()=>{})},[])
  function openAdd(){setForm({...emptyForm});setEditing(null);setShowForm(true);setError('')}
  function openEdit(room){setForm({roomType:room.roomType,description:room.description||'',pricePerNight:room.pricePerNight,maxOccupancy:room.maxOccupancy,totalUnits:room.totalUnits,facilities:room.facilities||[],images:room.images||[],breakfastIncluded:room.breakfastIncluded,freeCancellation:room.freeCancellation});setEditing(room.id);setShowForm(true);setError('')}
  async function save(e){e.preventDefault();setSaving(true);setError('');const payload={roomType:form.roomType,description:form.description,pricePerNight:Number(form.pricePerNight),maxOccupancy:Number(form.maxOccupancy),totalUnits:Number(form.totalUnits),facilities:form.facilities,images:form.images,breakfastIncluded:form.breakfastIncluded,freeCancellation:form.freeCancellation};try{if(editing) await api.put(`/owner/rooms/${editing}`,payload);else await api.post(`/owner/hotels/${id}/rooms`,payload);setShowForm(false);load()}catch(err){setError(err.response?.data?.message||'Could not save room.')}finally{setSaving(false)}}
  async function remove(){try{await api.delete(`/owner/rooms/${deleteTarget}`);setDeleteTarget(null);load()}catch(err){setError(err.response?.data?.message||'Could not delete room.')}}
  if(loading)return <Loader/>
  return <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 sm:py-10"><Link to="/owner/properties" className="text-primary text-sm hover:underline">← Back to properties</Link><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mt-2 mb-6"><div><h1 className="font-display font-bold text-2xl">{hotel?.name} — Rooms</h1><p className="text-slate-500 text-sm">Add photos first, then guests can reserve directly from those room cards.</p></div><button onClick={openAdd} className="btn-accent w-full sm:w-auto">+ Add room type</button></div>
    {error&&<p className="mb-4 bg-red-50 border border-red-100 text-red-700 rounded-lg px-3 py-2 text-sm">{error}</p>}
    <div className="space-y-4">{rooms.map(room=>{const imgs=room.images||[];return <article key={room.id} className="card overflow-hidden"><div className="grid grid-cols-1 md:grid-cols-3"><button onClick={()=>imgs.length&&setPreview(imgs)} className="relative h-60 md:h-full min-h-[250px] bg-slate-100 overflow-hidden">{imgs.length?<img src={imgs[0]} alt={room.roomType} className="w-full h-full object-cover hover:scale-105 transition"/>:<span className="flex h-full items-center justify-center text-slate-400">No room photos</span>}{imgs.length>1&&<span className="absolute left-3 bottom-3 bg-black/70 text-white text-xs font-semibold px-3 py-2 rounded-lg">📷 {imgs.length} photos</span>}</button><div className="md:col-span-2 p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:justify-between gap-3"><div><h2 className="font-display font-bold text-lg">{room.roomType}</h2><p className="text-sm text-slate-500">Sleeps {room.maxOccupancy} · {room.totalUnits} unit(s)</p></div><p className="text-primary font-extrabold text-lg">Rs {Number(room.pricePerNight).toLocaleString()}<span className="text-xs text-slate-400"> / night</span></p></div><div className="flex flex-wrap gap-1.5 mt-3">{(room.facilities||[]).map(f=><span key={f} className="chip text-xs">{f}</span>)}</div>{imgs.length>1&&<div className="grid grid-cols-5 gap-2 mt-4">{imgs.slice(0,5).map((img,i)=><button key={img+i} onClick={()=>setPreview(imgs)} className="h-16 rounded-lg overflow-hidden"><img src={img} alt="" className="w-full h-full object-cover"/></button>)}</div>}<div className="flex flex-wrap gap-2 mt-5 pt-4 border-t border-slate-100"><Link to={`/owner/rooms/${room.id}/calendar`} className="btn-outline text-sm py-2">Calendar</Link><button onClick={()=>openEdit(room)} className="btn-outline text-sm py-2">Edit</button><button onClick={()=>setDeleteTarget(room.id)} className="text-sm py-2 px-3 rounded-lg border border-red-200 text-red-600 font-semibold">Delete</button></div></div></div></article>})}</div>
    {!rooms.length&&<div className="card p-10 text-center text-slate-500">No room types yet. Add one to allow guests to book.</div>}
    {showForm&&<div className="fixed inset-0 z-[1000] bg-black/50 overflow-y-auto p-3 sm:p-5"><form onSubmit={save} className="bg-white rounded-2xl shadow-cardHover max-w-2xl w-full p-4 sm:p-6 my-3 sm:my-8 mx-auto space-y-4"><div className="flex items-center justify-between gap-3"><h3 className="font-display font-bold text-lg">{editing?'Edit room type':'Add room type'}</h3><button type="button" onClick={()=>setShowForm(false)} className="text-2xl text-slate-400">×</button></div><input required placeholder="Room type (e.g. Deluxe Double)" value={form.roomType} onChange={e=>setForm({...form,roomType:e.target.value})} className="input-field"/><textarea placeholder="Description" rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="input-field"/><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div><label className="text-xs text-slate-400 block mb-1">Price / night</label><input required type="number" min="0" value={form.pricePerNight} onChange={e=>setForm({...form,pricePerNight:e.target.value})} className="input-field"/></div><div><label className="text-xs text-slate-400 block mb-1">Max occupancy</label><input required type="number" min="1" value={form.maxOccupancy} onChange={e=>setForm({...form,maxOccupancy:e.target.value})} className="input-field"/></div><div><label className="text-xs text-slate-400 block mb-1">Units</label><input required type="number" min="1" value={form.totalUnits} onChange={e=>setForm({...form,totalUnits:e.target.value})} className="input-field"/></div></div><div><label className="text-xs text-slate-400 mb-2 block">Room facilities</label><FacilityChecklist masterList={master} selected={form.facilities} onChange={facilities=>setForm({...form,facilities})}/></div><MultiImageUpload images={form.images} onChange={images=>setForm({...form,images})} label="Room photos"/><div className="flex flex-col sm:flex-row gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.breakfastIncluded} onChange={e=>setForm({...form,breakfastIncluded:e.target.checked})} className="accent-primary w-4 h-4"/>Breakfast included</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.freeCancellation} onChange={e=>setForm({...form,freeCancellation:e.target.checked})} className="accent-primary w-4 h-4"/>Free cancellation</label></div>{error&&<p className="text-red-600 text-sm">{error}</p>}<div className="flex flex-col-reverse sm:flex-row justify-end gap-2 pt-2"><button type="button" onClick={()=>setShowForm(false)} className="btn-outline">Cancel</button><button type="submit" disabled={saving} className="btn-primary">{saving?'Saving…':'Save room'}</button></div></form></div>}
    {preview&&<div className="fixed inset-0 z-[2000] bg-black/95 flex items-center justify-center p-4" onClick={()=>setPreview(null)}><img src={preview[0]} alt="Room" className="max-h-[80vh] max-w-full object-contain"/><button className="absolute top-4 right-4 text-white text-3xl">×</button></div>}
    <ConfirmDialog open={!!deleteTarget} title="Delete this room type?" message="Guests will no longer be able to book this room type." confirmLabel="Delete room" danger onConfirm={remove} onCancel={()=>setDeleteTarget(null)}/>
  </div>
}