import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import api from '../../api/client.js'
import Loader from '../../components/Loader.jsx'

export default function AdminFacilities(){
 const [type,setType]=useState('hotel'); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [name,setName]=useState(''); const [editing,setEditing]=useState(null); const [error,setError]=useState('')
 function load(){setLoading(true);api.get(`/admin/facilities?type=${type}`).then(r=>setItems(r.data)).catch(e=>setError(e.response?.data?.message||'Could not load facilities.')).finally(()=>setLoading(false))}
 useEffect(()=>{load()},[type])
 async function save(e){e.preventDefault();if(!name.trim())return;setError('');try{if(editing)await api.put(`/admin/facilities/${editing}`,{name:name.trim(),type});else await api.post('/admin/facilities',{name:name.trim(),type});setName('');setEditing(null);load()}catch(e){setError(e.response?.data?.message||'Could not save facility.')}}
 async function remove(id){if(!window.confirm('Delete this facility? Existing properties keep their saved text, but it will disappear from future forms.'))return;try{await api.delete(`/admin/facilities/${id}`);load()}catch(e){setError(e.response?.data?.message||'Could not delete facility.')}}
 if(loading)return <Loader/>
 return <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 sm:py-10"><Link to="/admin" className="text-primary text-sm hover:underline">← Back to dashboard</Link><h1 className="font-display font-bold text-2xl mt-2">Hotel & room facilities</h1><p className="text-slate-500 text-sm mt-1 mb-6">Manage the master facility list used by owners when creating or editing properties and rooms.</p><div className="flex gap-2 mb-4"><button onClick={()=>setType('hotel')} className={type==='hotel'?'btn-primary':'btn-outline'}>Hotel facilities</button><button onClick={()=>setType('room')} className={type==='room'?'btn-primary':'btn-outline'}>Room facilities</button></div>{error&&<p className="text-red-600 text-sm mb-3">{error}</p>}<form onSubmit={save} className="card p-4 mb-5 flex flex-col sm:flex-row gap-2"><input value={name} onChange={e=>setName(e.target.value)} className="input-field flex-1" placeholder={`Add ${type} facility`}/><button className="btn-primary">{editing?'Update':'Add facility'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setName('')}} className="btn-outline">Cancel</button>}</form><div className="card divide-y divide-slate-100">{items.map(item=><div key={item.id} className="p-4 flex items-center justify-between gap-3"><span className="font-medium">{item.name}</span><div className="flex gap-2"><button onClick={()=>{setEditing(item.id);setName(item.name)}} className="btn-outline text-sm py-2">Edit</button><button onClick={()=>remove(item.id)} className="text-sm py-2 px-3 rounded-lg border border-red-200 text-red-600 font-semibold">Delete</button></div></div>)}{!items.length&&<p className="p-6 text-center text-slate-500">No facilities found.</p>}</div></div>
}